steps:
  # Build and deploy extract_metadata
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$_TRIGGER_NAME" == "audit-bill-routing" ]]; then
          cd extraction_routing
          gcloud functions deploy bill-extraction-routing --runtime=python312 --trigger-http --source=. --region=us-central1 --entry-point=extraction_routing --allow-unauthenticated;
        fi